version: 0.2
phases:
  pre_build:
    commands:
      - echo starting deployment `date`
  build:
    commands:
      - echo deployment started on `date`
      - ls
      - pwsh databrickcli.ps1
  post_build:
    commands:
      - echo Completed...